<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Application Namespace
    |--------------------------------------------------------------------------
    |
    | This value is the namespace of your application.
    |
     */
    'namespace' => 'App\\',


    /*
    |--------------------------------------------------------------------------
    | Application Admin URL
    |--------------------------------------------------------------------------
    |
    | This value is the URL of your admin application.
    |
     */
    'admin_app_url' => env('ADMIN_APP_URL', 'admin.' . env('APP_URL')),
    'admin_app_path' => env('ADMIN_APP_PATH', ''),

    /*
    |--------------------------------------------------------------------------
    | Admin subdomain routing support
    |--------------------------------------------------------------------------
    |
    | Enabling this allows adding top level keys to LegoCMS's navigation and
    | dashboard modules configuration, mapping to a subdomain.
    | This is a very simple way to implement multi-tenant CMS/sites in LegoCMS.
    | A navigation array looking like the following would expose your CMS on
    | the 'admin.subdomain1.app-url.test' and 'admin.subdomain2.app-url.test'
    | urls, with its corresponding links.
    | [
    |   'subdomain1' => [
    |     'module1' => [...],
    |     ...
    |   ],
    |   'subdomain2' => [
    |     'module2' => [...]
    |     ...
    |   ]
    | ]
    |
    | App name can be set per subdomain using the 'legocms.app_names'
    | configuration array. For our example above:
    | [
    |   'app_names' => [
    |     'subdomain1' => 'App 1 name',
    |     'subdomain2' => 'App 2 name',
    |   ],
    | ]
    |
    | Subdomain configuration nesting also applies to the dashboard
    | 'modules' key.
    |
    | You can provide a custom 'block_single_layout' per subdomain by
    | creating a Blade file under resources/views/subdomain/layouts/blocks.
    |
     */
    'support_subdomain_admin_routing' => false,
    'admin_app_subdomain' => 'admin',
    'active_subdomain' => null,

    /*
    |--------------------------------------------------------------------------
    | LegoCMS middleware group configuration
    |--------------------------------------------------------------------------
    |
    | Right now this only allows you to redefine the default login redirect path.
    |
    */
    'admin_middleware_group' => ['web'],

    /*
    |--------------------------------------------------------------------------
    | LegoCMS Auth related configuration
    |--------------------------------------------------------------------------
    |
     */
    'auth_login_redirect_path' => '/',
    'templates_on_frontend_domain' => false,

    /*
    |--------------------------------------------------------------------------
    | LegoCMS FrontEnd Application configurqtion
    |--------------------------------------------------------------------------
    |
     */
    'js_namespace' => 'LEGOCMS',
    'public_directory' => env('LEGOCMS_ASSETS_DIR', 'assets/admin'),


    'bind_exception_handler' => true,

    /*
    |--------------------------------------------------------------------------
    | LegoCMS default tables naming configuration
    |--------------------------------------------------------------------------
    |
     */
    'users_table' => 'legocms_users',
    'password_resets_table' => 'legocms_password_resets',


    /*
    |--------------------------------------------------------------------------
    | LegoCMS migrations configuration
    |--------------------------------------------------------------------------
    |
    | Since Laravel 5.8, migrations generated by Laravel use big integers
    | on the `id` column. LegoCMS migrations helpers can be configured to
    | use regular integers for backwards compatiblity.
    |
    | TODO: Remove this as the base support is greater than Laravel 5.8
    |
     */
    'migrations_use_big_integers' => true,

    /*
    |--------------------------------------------------------------------------
    | LegoCMS app locale
    |--------------------------------------------------------------------------
    |
     */
    'locale' => 'en',
    'fallback_locale' => 'en',
];
